#  github: @captam3rica

#
#   This is a TOML config file for resources pertaining to the WorkspaceONE API
#   calls.
#
#   Resources:
#
#       - https://github.com/toml-lang/toml
#       - documentation - https://toml.io/en/v1.0.0
#

[version]
config_version = "1.1"

[customer]
customer_name = "customer_name_here"

[mdm_info]
vendor = "🐝"
base_url = "https://example.clients.us-1.kandji.io/api"

[api_info]
authorization = """Bearer <Kandji_Bearer_Token>"""
accept = "application/json"
content_type = "application/json;charset=utf-8"
cache_control = "no-cache"

[log_config]
###############################################################################
# Set the appropriate log level
#   10 = DEBUG
#   20 = INFO
#   30 = WARNING
#   40 = ERROR
###############################################################################
log_level = 10
# Replace customer name with actual customer name. TOML does not support variable
# substitution
log_file_path = "/Library/Logs"  # If a path is not set the default will be set to "/Library/Logs/apu/.
